# Generated by Django 3.1.4 on 2020-12-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemagen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
