# Generated by Django 3.1.4 on 2020-12-30 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schemagen', '0003_schema_schema_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='_type',
        ),
        migrations.AddField(
            model_name='field',
            name='kind',
            field=models.CharField(choices=[('FULL_NAME', 'Full name'), ('JOB', 'Job')], default="Temporary TypeYou are trying to add a non-nullable field 'order' to schema_field without a default; we can't do that (the database needs something to populate existing rows).\nPlease select a fix:\n 1) Provide a one-off default now (will be set on all existing rows with a null value for this column)\n 2) Quit, and let me add a default in models.py\n", max_length=64),
        ),
        migrations.AlterField(
            model_name='schema_field',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='schemagen.schema'),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
