# Generated by Django 3.1.4 on 2020-12-30 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schemagen', '0003_schema_schema_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='_type',
        ),
        migrations.AddField(
            model_name='field',
            name='kind',
            field=models.CharField(choices=[('FULL_NAME', 'Full name'), ('JOB', 'Job')], max_length=64),
        ),
        migrations.AlterField(
            model_name='schema_field',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='schemagen.schema'),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
