# Generated by Django 3.1.4 on 2021-01-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemagen', '0004_auto_20201230_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='kind',
            field=models.CharField(choices=[('FULL_NAME', 'Full name'), ('JOB', 'Job'), ('Sity', 'Sity')], default='Temporary Type', max_length=64),
        ),
        migrations.AlterField(
            model_name='field',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
