# Generated by Django 3.1.5 on 2021-01-08 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schemagen', '0005_auto_20210105_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='schema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='schemagen.schema'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='field',
            name='kind',
            field=models.CharField(choices=[('FULL_NAME', 'Full name'), ('Job', 'Job'), ('Sity', 'Sity')], default='Temporary Type', max_length=64),
        ),
        migrations.DeleteModel(
            name='Schema_Field',
        ),
    ]
